name: Daily Blog Generation and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai pillow requests python-slugify beautifulsoup4 firebase-admin
    
    - name: Generate new blog post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/generate_blog.py
    
    - name: Fetch and process image
      env:
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      run: |
        # Extract slug and city from the generated blog info
        SLUG=$(ls -t blog/*.html | head -n1 | sed 's/.*\/\(.*\)\.html/\1/')
        CITY=$(grep -o 'Find Flights to [^<]*' "blog/$SLUG.html" | sed 's/Find Flights to //')
        python scripts/fetch_image.py "$SLUG" "$CITY"
    
    - name: Update blog index
      run: |
        python scripts/update_blog_index.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit changes
      run: |
        git add .
        git commit -m "Add new blog post [skip ci]" || echo "No changes to commit"
        git push
    
    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --token "$FIREBASE_TOKEN" --only hosting 